FROM node:16-alpine AS builder
WORKDIR /app/src
COPY --chown=node:node cx-admin-search-app-ui/ui/package*.json .
RUN npm ci
COPY --chown=node:node cx-admin-search-app-ui/ui /app/src
RUN npm run build
ENV NODE_ENV production
RUN npm ci --only=production && npm cache clean --force
USER node

FROM nginx:1.21.0-alpine as production
COPY --chown=node:node --from=builder /app/src/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8083
CMD ["nginx", "-g", "daemon off;"]