server:
  jetty:
    threads:
      idle-timeout: 1000
      max: 20
      min: 10
  port: 8080
  servlet:
    contextPath: /

management:
  endpoint:
    health:
      group:
        readiness:
          include: ping
        liveness:
          include: ping
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
  server:
    port: 8081

logging:
  file.name: ./cx-admin-search-app-service/service/log/app.log
  level:
    web: INFO

account-service:
  host: ${ACCOUNT_SERVICE_HOST:http://account-services.private.be.int05.integration.pgt.gaia}
  path: /account-api/v2/accounts
  api-key: ${ACCOUNT_SERVICE_API_KEY:api-key}